---  
layout: post  
title: "[Swift] - case let"  
subtitle: ""  
categories: app
tags: app-swift case let
comments: true  
header-img: 
---  
  
> `case let`  

---

[https://stevenpcurtis.medium.com/ive-finally-mastered-case-let-in-my-swift-code-7b1737cf52c3](https://stevenpcurtis.medium.com/ive-finally-mastered-case-let-in-my-swift-code-7b1737cf52c3)


JSON 문자열을 다운받아서 결과를 화면에 출력하는 코드가 있다고 해보자. 이 때 사용하는 completionHandler에는 JSON 데이터를 올바르게 잘 
받은 경우에 `((Users) -> Void)?` 클로저를 리턴한다.

Result 타입을 리턴하는 것은 복잡도를 증가시킨다. 백엔드나 그 외에서 리턴된 에러에 대해서도 생각해봐야 한다. 이런 에러를 핸들링 하기 위해
viewModel을 사용할 수 있다. `ViewModel`이 아래의 클로저를 리턴해서 사용하게 할 수 있다.

```swift
var closure: ((Result<Users, Error>) -> Void)?
```

구현은 아래와 같이 될 것이다.

```swift
viewModel.closure = { result in
  switch result {
    case let .success(users):
      print(users.data.map{ "\($0.firstName)"}.joined(separator:"\n"))
    case .failure(_):
      break
  }
}
```

위 코드에서 문제는 무엇이냐면 fail일 때의 case를 핸들링하고 있지만, 여기서 아무 작업도 하고 있지 않기 때문에 break를 작성한 것인데,
별로 이 코드에 도움이 되지 않는다. 이는 아래와 같이 개선될 수 있다.

```swift
viewModel.closure = { result in
  if case let .success(users) = result {
      print(users.data.map{ "\($0.firstName)"}.joined(separator:"\n"))
  }
}
```

* 참고
* https://townpharm.tistory.com/12
